version: "3.7"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./data/esdata01:/usr/share/elasticsearch/data
      - ./certs:$CERTS_DIR

    ports:
      - ${ES_PORT}:9200
    environment:
      - xpack.security.enabled=true
      - node.name=es01
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/elk.key
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/elk.crt
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/elk.key
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/elk.crt
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

    networks:
      - elastic

##  kibana:
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - ./data/kibana:/usr/share/kibana/data
      - ./certs:/usr/share/kibana/certs
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/config/certs/elk.crt
      - SERVER_SSL_KEY=/usr/share/kibana/certs/elk.key
      - SERVER_SSL_KEYPASSPHRASE=${KEYPASSPHRASE}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - xpack.security.http.ssl.certificate_authorities=/usr/share/kibana/certs/ca.crt
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/certs/ca.crt
    networks:
      - elastic
    depends_on:
      - es01

networks:
  elastic: